### ISSUE TITLE
Define database models

### ISSUE THREAD

**Issue by JantjeJoppien** [JantjeJoppien/HomeManager#1]
First data structures are defined

**Comment by mvxsvchs** [comment]
Data needed: 

Model A: 
- id (primary key)
- name
- amount 
- brand (optional) 
- price (optional)
- best before 
- category

Model B: 
- id (primary key)
- name
- amount 
- brand (optional) 
- price (optional)
- bought on 
- origin (optional)
- category

Model C: 
- id (primary key)
- name
